### PR TITLE
Refactor module to allow install with `pip install git+https://github.com/acl-org/aclpubcheck` and execution with `aclpubcheck -p long PAPER_NAME.pdf`

### PR DESCRIPTION
**Pull request by xhluca**
I'm making this PR since I can't directly push to another fork: https://github.com/acl-org/aclpubcheck/pull/40#discussion_r1476303954

> Yes, this makes sense to me. Please feel free to make the modification since I'm still waiting for this to be included.

In addition to the CLI proposed in #40, I am including:
- install using pip directly from github, avoiding having to go through pypi release process: `pip install git+https://github.com/acl-org/aclpubcheck`
- option to call with script execution: `aclpubcheck -p ...`
- option to call with [module execution](https://stackoverflow.com/questions/7610001/what-is-the-purpose-of-the-m-switch) (when script execution is not possible): `python3 -m aclpubcheck -p ...`
- updated readme with detailed explanation of how to install and use the pubcheck toolkit
- limit the version for `rebiber` to be below 2.0.0 (which introduces a breaking change that would completely break aclpubcheck)

Note that there are no external dependencies needed (e.g., poetry, pipenv, etc.). 

For testing purposes, you can install directly from my fork:

```bash
# virtualenv to avoid 
python -m venv venv-acl
source venv-acl/bin/activate

# install from my forked repo, if merged we can replace `xhluca` with `acl-org`
pip install git+https://github.com/xhluca/aclpubcheck

# download example pdf
wget https://github.com/xhluca/aclpubcheck/blob/main/example/2023.acl-tutorials.1.pdf

# test the fork
aclpubcheck -p long 2023.acl-tutorials.1.pdf

python -m aclpubcheck -p long 2023.acl-tutorials.1.pdf
```

### CODE REVIEW

**Comment by xhluca** [comment]
@crux82 I've simplified the colab notebook with the new command line approach. It can be found here: 

https://colab.research.google.com/github/xhluca/aclpubcheck/blob/main/aclpubcheck_online.ipynb

If this PR is merged, the link will be accessible at: https://colab.research.google.com/github/acl-org/aclpubcheck/blob/main/aclpubcheck_online.ipynb

This link is directly linked to the ipynb file located in the repository, which means the Colab notebook will be updated when the repository is updated.

**Comment by crux82** [comment]
Dear all,

first, thank you for your excellent work!

If you see no problems, I will merge in a few days. These days, the deadline for submitting the EACL (and the 19 Workshops) camera ready is expiring. As (also) publication chair of EACL, I would like to avoid any surprises. As soon as this phase is closed, I will merge. Sorry if it seems I have not followed up on the good work done

**Comment by xhluca** [comment]
Thanks for the update! Makes sense to minimize disruption.

**Comment by xhluca** [comment]
@crux82 Let me know if anything is needed on my end!

**Comment by crux82** [comment]
Sorry @xhluca, I was distracted by the EACL proceedings. Great work

@teelinsan can you please check if the version on Gradio still works?

**Comment by teelinsan** [comment]
@crux82 I confirm that the Gradio version is still working

**Comment by crux82** [comment]
great!

**Pull request merged**
